# Generated by Django 3.2.5 on 2021-08-01 19:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20210730_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='description_ge',
            field=models.TextField(blank=True, null=True, verbose_name='Description (GE)'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (RU)'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location on map'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='src.Tag'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='url_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook page'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='url_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram page'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='url_main',
            field=models.URLField(blank=True, null=True, verbose_name='Main url (e.g., website url)'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='url_twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter account'),
        ),
    ]
